version: '3'

services:

  icecast:
    image: canarysat/alpine-icecast:latest
    network_mode: bridge
    restart: always
    container_name: icecast
    ports:
    - "8000:8000"
    volumes:
    - '$PWD/config:/etc/icecast2'
    - '$PWD/logs:/var/log/icecast2'
    environment:
    - ICECAST_SOURCE_PASSWORD=abcd
    - ICECAST_ADMIN_PASSWORD=123456
    - ICECAST_RELAY_PASSWORD=abcd
    - ICECAST_ADMIN_USERNAME=admin
    - ICECAST_ADMIN_EMAIL=peter@canarysat.com
    - ICECAST_LOCATION=CanarySAT Server Streaming
    - ICECAST_HOSTNAME=CanarySAT-Radios
    - ICECAST_MAX_CLIENTS=100
    - ICECAST_MAX_SOURCES=2
